kind: Pod
apiVersion: v1
metadata:
  name: resource
spec:
  containers:
  - name: nginx
    image:  nginx
    resources:
        #soft limit
      requests:
        memory: "68Mi"
        cpu: "100m"
        #Hard limit
      limit:
        memory: "126Mi"
        cpu: "150m"
